name: Autograding Tests
on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
env:
  IMG_URL_riscv64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-riscv64.img.gz # 镜像url
  IMG_URL_loongarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-loongarch64.img.gz # 镜像url
  IMG_URL_aarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-aarch64.img.gz # 镜像url
  IMG_URL_x86_64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-x86_64.img.gz # 镜像url
  TIMEOUT: 300 # 超时时间
  SCRIPT_REPO: https://github.com/oscontent25/EvaluationScript # 脚本仓库
  
jobs:  
  run-autograding-tests:
    runs-on: ubuntu-latest
    env:
      qemu-version: 9.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-01-18
          components: rust-src, llvm-tools
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-binutils
      - uses: ./.github/workflows/setup-musl
        with:
          arch: riscv64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: loongarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: aarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: x86_64
      - uses: ./.github/workflows/setup-qemu
        with:
          qemu-version: ${{ env.qemu-version }}
      - name: Build python environment
        run: sudo apt-get install -y python3 python3-pip
      - name: build os.bin
        run: |
          touch riscv64_output.txt
          touch loongarch64_output.txt
          touch aarch64_output.txt
          touch x86_64_output.txt
          make oscomp_run ARCH=riscv64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > riscv64_output.txt || true
          make clean
          make oscomp_run ARCH=loongarch64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > loongarch64_output.txt || true
          make clean
          make oscomp_run ARCH=aarch64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > aarch64_output.txt || true
          make clean
          make oscomp_run ARCH=x86_64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs ACCEL=n > x86_64_output.txt || true

      - name: Download EvaluationScript
        run: |
            git clone ${{ env.SCRIPT_REPO }} .github/classroom

      - name: riscvglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: riscvglibcbasic-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: loongarchglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibcbasic-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: aarchglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: aarchglibcbasic-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: x86glibcbasic-test
        uses: oscontent25/os-autograding@master
        id: x86glibcbasic-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: riscvglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: riscvglibclibctest-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: loongarchglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibclibctest-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: aarchglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: aarchglibclibctest-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: x86glibclibctest-test
        uses: oscontent25/os-autograding@master
        id: x86glibclibctest-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: riscvglibclua-test
        uses: oscontent25/os-autograding@master
        id: riscvglibclua-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: loongarchglibclua-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibclua-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: aarchglibclua-test
        uses: oscontent25/os-autograding@master
        id: aarchglibclua-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: x86glibclua-test
        uses: oscontent25/os-autograding@master
        id: x86glibclua-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: riscvglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: riscvglibcbusybox-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: loongarchglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibcbusybox-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: aarchglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: aarchglibcbusybox-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: x86glibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: x86glibcbusybox-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: riscvglibciozone-test
        uses: oscontent25/os-autograding@master
        id: riscvglibciozone-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: loongarchglibciozone-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibciozone-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: aarchglibciozone-test
        uses: oscontent25/os-autograding@master
        id: aarchglibciozone-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: x86glibciozone-test
        uses: oscontent25/os-autograding@master
        id: x86glibciozone-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: riscvmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: riscvmuslbasic-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: loongarchmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: loongarchmuslbasic-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: aarchmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: aarchmuslbasic-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: x86muslbasic-test
        uses: oscontent25/os-autograding@master
        id: x86muslbasic-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: riscvmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: riscvmusllibctest-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: loongarchmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusllibctest-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: aarchmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: aarchmusllibctest-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: x86musllibctest-test
        uses: oscontent25/os-autograding@master
        id: x86musllibctest-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: riscvmusllua-test
        uses: oscontent25/os-autograding@master
        id: riscvmusllua-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: loongarchmusllua-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusllua-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: aarchmusllua-test
        uses: oscontent25/os-autograding@master
        id: aarchmusllua-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: x86musllua-test
        uses: oscontent25/os-autograding@master
        id: x86musllua-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: riscvmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: riscvmuslbusybox-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: loongarchmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: loongarchmuslbusybox-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: aarchmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: aarchmuslbusybox-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: x86muslbusybox-test
        uses: oscontent25/os-autograding@master
        id: x86muslbusybox-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: riscvmusliozone-test
        uses: oscontent25/os-autograding@master
        id: riscvmusliozone-test
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: loongarchmusliozone-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusliozone-test
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: aarchmusliozone-test
        uses: oscontent25/os-autograding@master
        id: aarchmusliozone-test
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: x86musliozone-test
        uses: oscontent25/os-autograding@master
        id: x86musliozone-test
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-iozone
      
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          RISCVGLIBCBASIC-TEST_RESULTS: "${{steps.riscvglibcbasic-test.outputs.result}}"
          LOONGARCHGLIBCBASIC-TEST_RESULTS: "${{steps.loongarchglibcbasic-test.outputs.result}}"
          AARCHGLIBCBASIC-TEST_RESULTS: "${{steps.aarchglibcbasic-test.outputs.result}}"
          X86GLIBCBASIC-TEST_RESULTS: "${{steps.x86glibcbasic-test.outputs.result}}"
          RISCVGLIBCLIBCTEST-TEST_RESULTS: "${{steps.riscvglibclibctest-test.outputs.result}}"
          LOONGARCHGLIBCLIBCTEST-TEST_RESULTS: "${{steps.loongarchglibclibctest-test.outputs.result}}"
          AARCHGLIBCLIBCTEST-TEST_RESULTS: "${{steps.aarchglibclibctest-test.outputs.result}}"
          X86GLIBCLIBCTEST-TEST_RESULTS: "${{steps.x86glibclibctest-test.outputs.result}}"
          RISCVGLIBCLUA-TEST_RESULTS: "${{steps.riscvglibclua-test.outputs.result}}"
          LOONGARCHGLIBCLUA-TEST_RESULTS: "${{steps.loongarchglibclua-test.outputs.result}}"
          AARCHGLIBCLUA-TEST_RESULTS: "${{steps.aarchglibclua-test.outputs.result}}"
          X86GLIBCLUA-TEST_RESULTS: "${{steps.x86glibclua-test.outputs.result}}"
          RISCVGLIBCBUSYBOX-TEST_RESULTS: "${{steps.riscvglibcbusybox-test.outputs.result}}"
          LOONGARCHGLIBCBUSYBOX-TEST_RESULTS: "${{steps.loongarchglibcbusybox-test.outputs.result}}"
          AARCHGLIBCBUSYBOX-TEST_RESULTS: "${{steps.aarchglibcbusybox-test.outputs.result}}"
          X86GLIBCBUSYBOX-TEST_RESULTS: "${{steps.x86glibcbusybox-test.outputs.result}}"
          RISCVGLIBCIOZONE-TEST_RESULTS: "${{steps.riscvglibciozone-test.outputs.result}}"
          LOONGARCHGLIBCIOZONE-TEST_RESULTS: "${{steps.loongarchglibciozone-test.outputs.result}}"
          AARCHGLIBCIOZONE-TEST_RESULTS: "${{steps.aarchglibciozone-test.outputs.result}}"
          X86GLIBCIOZONE-TEST_RESULTS: "${{steps.x86glibciozone-test.outputs.result}}"
          RISCVMUSLBASIC-TEST_RESULTS: "${{steps.riscvmuslbasic-test.outputs.result}}"
          LOONGARCHMUSLBASIC-TEST_RESULTS: "${{steps.loongarchmuslbasic-test.outputs.result}}"
          AARCHMUSLBASIC-TEST_RESULTS: "${{steps.aarchmuslbasic-test.outputs.result}}"
          X86MUSLBASIC-TEST_RESULTS: "${{steps.x86muslbasic-test.outputs.result}}"
          RISCVMUSLLIBCTEST-TEST_RESULTS: "${{steps.riscvmusllibctest-test.outputs.result}}"
          LOONGARCHMUSLLIBCTEST-TEST_RESULTS: "${{steps.loongarchmusllibctest-test.outputs.result}}"
          AARCHMUSLLIBCTEST-TEST_RESULTS: "${{steps.aarchmusllibctest-test.outputs.result}}"
          X86MUSLLIBCTEST-TEST_RESULTS: "${{steps.x86musllibctest-test.outputs.result}}"
          RISCVMUSLLUA-TEST_RESULTS: "${{steps.riscvmusllua-test.outputs.result}}"
          LOONGARCHMUSLLUA-TEST_RESULTS: "${{steps.loongarchmusllua-test.outputs.result}}"
          AARCHMUSLLUA-TEST_RESULTS: "${{steps.aarchmusllua-test.outputs.result}}"
          X86MUSLLUA-TEST_RESULTS: "${{steps.x86musllua-test.outputs.result}}"
          RISCVMUSLBUSYBOX-TEST_RESULTS: "${{steps.riscvmuslbusybox-test.outputs.result}}"
          LOONGARCHMUSLBUSYBOX-TEST_RESULTS: "${{steps.loongarchmuslbusybox-test.outputs.result}}"
          AARCHMUSLBUSYBOX-TEST_RESULTS: "${{steps.aarchmuslbusybox-test.outputs.result}}"
          X86MUSLBUSYBOX-TEST_RESULTS: "${{steps.x86muslbusybox-test.outputs.result}}"
          RISCVMUSLIOZONE-TEST_RESULTS: "${{steps.riscvmusliozone-test.outputs.result}}"
          LOONGARCHMUSLIOZONE-TEST_RESULTS: "${{steps.loongarchmusliozone-test.outputs.result}}"
          AARCHMUSLIOZONE-TEST_RESULTS: "${{steps.aarchmusliozone-test.outputs.result}}"
          X86MUSLIOZONE-TEST_RESULTS: "${{steps.x86musliozone-test.outputs.result}}"

        with:
          runners: riscvglibcbasic-test,loongarchglibcbasic-test,aarchglibcbasic-test,x86glibcbasic-test,riscvglibclibctest-test,loongarchglibclibctest-test,aarchglibclibctest-test,x86glibclibctest-test,riscvglibclua-test,loongarchglibclua-test,aarchglibclua-test,x86glibclua-test,riscvglibcbusybox-test,loongarchglibcbusybox-test,aarchglibcbusybox-test,x86glibcbusybox-test,riscvglibciozone-test,loongarchglibciozone-test,aarchglibciozone-test,x86glibciozone-test,riscvmuslbasic-test,loongarchmuslbasic-test,aarchmuslbasic-test,x86muslbasic-test,riscvmusllibctest-test,loongarchmusllibctest-test,aarchmusllibctest-test,x86musllibctest-test,riscvmusllua-test,loongarchmusllua-test,aarchmusllua-test,x86musllua-test,riscvmuslbusybox-test,loongarchmuslbusybox-test,aarchmuslbusybox-test,x86muslbusybox-test,riscvmusliozone-test,loongarchmusliozone-test,aarchmusliozone-test,x86musliozone-test
          token: ${{ secrets.GITHUB_TOKEN }}

        
